services:
  postgres:
    image: postgres:17

    container_name: masil-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: masil
      POSTGRES_PASSWORD: masil123
      POSTGRES_DB: masil

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: